openapi: 3.0.1
info:
  title: MyShot API
  description: Myshop is a service where you can buy products with offers and discounts
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/myshop-service'
paths:
  /myshop/cart/total:
    post:
      summary: Get the total amount of my cart
      description: Get the total amount of my cart including offers and discounts.
      operationId: getTotalAmountOfMyCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyCartRequest'
        description: List of products to purchase
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyCartResponse'
        '400':
          description: Bad request error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
        - id
      properties:
        name:
          type: string
        price:
          type: number
          format: double
        id:
          type: integer
    MyCartRequest:
      type: object
      required:
        - products
      properties:
        products:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Product'
      title: MyCartRequest
    MyCartResponse:
      type: object
      required:
        - subtotal
        - tax
        - total
        - comments
      properties:
        subtotal:
          type: number
          format: double
        tax:
          type: number
          format: double
        total:
          type: number
          format: double
        comments:
          type: string
        discounts:
          type: array
          items:
            type: string
      title: MyCartResponse
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      title: ErrorResponse